name: Password Checker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run test for Branch 1
      run: |
        python trabalho3/teste_branch1.py

    - name: Run test for Branch 2
      run: |
        pytest trabalho3/teste_branch2.py
