name: Password Checker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}


    - name: Run test for Branch 1
      run: |
        python teste_branch1.py

    - name: Run test for Branch 2
      run: |
        pytest teste_branch2.py
